### ISSUE TITLE
Request for some more features

### ISSUE THREAD

**Issue by lon** [KSF-Media/gitlab-dashboard#27]
This dashboard is working nice and have many of the features I was looking for (pipelines from all projects, looks nice, sorted list of the results, etc.) When testing I see some more features I would like to have, that you might consider adding if they make sense to you:

- Consider a config-file to be able to store gitlab_url and private_token if not given as parameters in the  URL, or some other way of delivering these parameters via environment variables (neat to have if you want to set up the one-and-only dashboard for a group of people and running this as a container in kubernetes for example...)
- Option to choose to display name of the person who has done the commit (not just the avatar)
- Option to display the namespace of the project

**Comment by f-f** [comment]
Hi @lon!

Personally I prefer the url-params configuration, so you can deploy anywhere and configure from the client (e.g. we use the [Github Pages hosted deployment](https://ksf-media.github.io/gitlab-dashboard/) for our dashboard at work), but I'd be open to have a "fallback" config method, e.g. via envvars as you mentioned, if some option is not provided via url-params.

Feel free to open separate issues for every single point of your list, and if you'd like to start working on any of them I can provide some guidance 👍

**Comment by lon** [comment]
:) I guess we're all missing "available time", but in addition I think my skills require "available time" to improve my skills to be up for it. Should I still open separate issues?

**Comment by f-f** [comment]
@lon the project is basically feature-complete from our point of view, so we are happy to maintain it, fix bugs, give guidance and review external contributions, but cannot allocate more resources to it (due to business constraints).
Moreover, I personally believe that picking up some Purescript is an experience totally worth the time :)

> Should I still open separate issues?

Sure 👍

**Comment by lon** [comment]
@f-f I fully understand your priorities.

Opened short separate issues for this, and I'm closing this one.
