### ISSUE TITLE
Blank page when manual tasks presents in project

### ISSUE THREAD

**Issue by aniyazov93** [KSF-Media/gitlab-dashboard#28]
Issue came from conversation in PR #26 

I sometimes get blank pages. In js console I see attempts to fetch tasks from project and error:

`Polling failed with error: Failed to parse jobs: (NonEmptyList (NonEmpty (ErrorAtProperty "pipeline" (ErrorAtProperty "status" (ForeignError "Expected \"running\" tag for unary constructor literal running"))) ((ErrorAtProperty "pipeline" (ErrorAtProperty "status" (ForeignError "Expected \"pending\" tag for unary constructor literal pending"))) : (ErrorAtProperty "pipeline" (ErrorAtProperty "status" (ForeignError "Expected \"success\" tag for unary constructor literal success"))) : (ErrorAtProperty "pipeline" (ErrorAtProperty "status" (ForeignError "Expected \"failed\" tag for unary constructor literal failed"))) : (ErrorAtProperty "pipeline" (ErrorAtProperty "status" (ForeignError "Expected \"canceled\" tag for unary constructor literal canceled"))) : (ErrorAtProperty "pipeline" (ErrorAtProperty "status" (ForeignError "Expected \"skipped\" tag for unary constructor literal skipped"))) : Nil)))
`

I think in some jobs presents unexpected values and script hangs, but after some time bad task goes away (script poll only 100 items) and dashboard begin work again.

I use gitlab-ce omnibus 11.1.4 (63daf37)

---
In conversation we made assumption what errors happens when script find a job with 'manual' task type, which is undocumented in gitlab docs.

I will try to reproduce it on my environment to get more details

**Comment by aniyazov93** [comment]
Yes, it reproducing with simple task like this:
```
---
stages:
  - test

bug_test:
  stage: test
  tags: 
    - shell
  only:
    - master
  script:
    - echo "Hello!"
  when: manual
  allow_failure: false

```

And responce for job api request looks like that:

```
[  
   {  
      "id":14947,
      "status":"manual",
      "stage":"test",
      "name":"bug_test",
      "ref":"master",
      "tag":false,
      "coverage":null,
      "created_at":"2018-08-14T19:02:19.484+03:00",
      "started_at":null,
      "finished_at":null,
      "duration":null,
     ...
   }
]
```

**Comment by f-f** [comment]
@radium88 note that you're referring to the `status` field of a Job, while the problematic bit seems to be the `status` of a Pipeline.  
So in your API response there should be a `pipeline` field containing some object, e.g.:

```
[
  {
    "id": 6,
    ...
    "pipeline": {
      "id": 6,
      "ref": "master",
      "sha": "0ff3ae198f8601a285adcf5c0fff204ee6fba5fd",
      "status": "pending"
    },
   ...
  }
]
```

What's the value of `status` in that object?

**Comment by aniyazov93** [comment]
It's 'manual' too.


`pipeline: {id: 3422, sha: "8622e405aa781de7b53f31eef4dd8c0b00609dcd", ref: "master", status: "manual"}`

**Comment by f-f** [comment]
@radium88 this should be fixed in the latest commit to `master`. Could you test the new changes and see if it works?

**Comment by aniyazov93** [comment]
Yeah, looks like all works fine now, thanks!
