### ISSUE TITLE
Port 'View' functions to purescript

### ISSUE THREAD

**Issue by zudov** [KSF-Media/gitlab-dashboard#3]
The current JS code has quite a lot of nicely contained functions that take some parameters and return HTML strings.

All of those can be very easily ported to functions that take parameters and return Halogen's [`HTML`](https://pursuit.purescript.org/packages/purescript-halogen/3.0.1/docs/Halogen#t:HTML).

We can put all of that into a separate module (e.g. `Dashboard.View`) and then just use them for rendering when we define the actual halogen application.

**Comment by f-f** [comment]
Closed by #6
