### ISSUE TITLE
Cross-origin request blocked - blank page

### ISSUE THREAD

**Issue by jcberthon** [KSF-Media/gitlab-dashboard#32]
When trying using this nice dashboard, I get always a blank page.

This is the Web console logs:

```
Fetching list of projects..
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gitlab.vcs.de/gitlab/api/v4/projects?private_token=**************&simple=true&per_page=20&order_by=last_activity_at. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
Polling failed with error: AJAX request failed: GET https://gitlab.vcs.de/gitlab/api/v4/projects?private_token=**************&simple=true&per_page=20&order_by=last_activity_at app.js:3562:7
```

Note that if I click on the link it does work, so my URL and my token are correct. But it seems that Firefox (61.0.2 64bit Linux) is blocking this request for security reasons. I guess if I would host the dashboard on the same host as the GitLab instance, that would bypass the same origin policy and work.

But I would still expect to be able to run the dashboard on a different host?

**Comment by aniyazov93** [comment]
Your gitlab instance is not allowing cross-origin requests. In my case gitlab is proxied via nginx, and I added rules to add missing headers:

add_header Access-Control-Allow-Origin * always;
add_header Access-Control-Allow-Headers * always;

Allowing all origins is not a good practice, but it works for me.

**Comment by aniyazov93** [comment]
And I think [this](https://docs.gitlab.com/omnibus/settings/nginx.html#inserting-custom-settings-into-the-nginx-config) may help you add CORS parameters into your instance of gitlab

**Comment by jcberthon** [comment]
Hi @radium88 

Thank you very much for potentially finding the problem, I need to check my GitLab/nginx logs. I will try to find another solution though. I usually try to keep security feature activated, e.g. I'm still running SELinux activated ;-)

One thing which bugs me though is that we have a few other external services using the GitLab API and we do not get this same origin problem... I need to do some log checking and maybe network tracing...

**Comment by f-f** [comment]
@jcberthon CORS is usually strictly enforced in browsers only, so it might be that your other services are not enforcing it, so everything is fine for them.  
As for keeping security tight, the right way to honour CORS in your case would be to add the host on which you're hosting the dashboard to the allowed origins of the Gitlab instance.

**Comment by f-f** [comment]
Since it doesn't seem to be an issue with the project but more with how your instance is configured, I'll close.  
@jcberthon feel free to reopen if you find out the problem is on our end 👍
